apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: txrx3wb8y-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-qe-jsmid/txrx3wb8y-java-quarkus-gitops